M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date 21.05.2024 (вт) 14:55:47
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-21T14:55:47+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.300
%
G90
G05
T1
X5.53Y18.89
X5.53Y13.11
T2
X48.0Y52.86
X48.0Y7.14
T3
X4.0Y36.0
X10.0Y36.0
T4
X4.0Y119.65
X4.0Y4.65
X37.0Y119.65
X37.0Y4.65
M30
